<?php

/**
 * Bancard vPOS Payment Gateway Library for FusionCMS
 *
 * Based on: https://github.com/krugerdavid/woocommerce-bancard-payments
 * Bancard API docs: https://comercios.bancard.com.py
 * API version: vPOS 0.3
 *
 * Key specs:
 *  - Operation token : MD5(private_key + shop_process_id + amount + currency)
 *  - Confirm token   : MD5(private_key + shop_process_id + "confirm" + amount + currency)
 *  - shop_process_id : integer, max 15 digits, format YYYYMMDD+orderId+attempt
 *  - amount          : string "165000.00" (2 decimal places, PYG = whole number)
 *  - Response codes  : "0", "00", "000" = APPROVED
 *  - IPN response    : always return HTTP 200 + { "status": "success" }
 */
class Bancard_lib
{
    const API_PRODUCTION = 'https://vpos.infonet.com.py';
    const API_TEST = 'https://vpos.infonet.com.py:8888';

    protected string $publicKey;
    protected string $privateKey;
    protected bool $testMode;
    protected string $currency;
    protected int $timeout = 30;

    public function __construct(string $publicKey, string $privateKey, bool $testMode = false, string $currency = 'PYG')
    {
        $this->publicKey = $publicKey;
        $this->privateKey = $privateKey;
        $this->testMode = $testMode;
        $this->currency = $currency;
    }

    // ─────────────────────────────────────────
    //  SHOP PROCESS ID  (max 15 digits integer)
    //  Format: YYYYMMDD + orderId + attempt
    // ─────────────────────────────────────────

    /**
     * Generate a unique shop_process_id for this order + attempt
     * Bancard does NOT allow reusing the same shop_process_id.
     */
    public function generateShopProcessId(string $orderId, int $attempt = 1): string
    {
        $date = date('Ymd'); // 8 digits
        $attemptStr = (string)$attempt; // 1-2 digits
        $maxOrder = 15 - 8 - strlen($attemptStr); // remaining digits for order

        if (strlen($orderId) > $maxOrder) {
            $orderId = substr($orderId, -$maxOrder);
        }

        $shopProcessId = $date . $orderId . $attemptStr;

        // Ensure it's a valid integer and ≤ 15 digits
        $shopProcessId = (string)(int)$shopProcessId;
        if (strlen($shopProcessId) > 15) {
            $shopProcessId = substr($shopProcessId, -15);
        }

        return $shopProcessId;
    }

    // ─────────────────────────────────────────
    //  TOKEN GENERATION
    // ─────────────────────────────────────────

    /**
     * Operation token: MD5(private_key + shop_process_id + amount + currency)
     */
    public function generateOperationToken(string $shopProcessId, string $amount): string
    {
        return md5($this->privateKey . $shopProcessId . $amount . $this->currency);
    }

    /**
     * Confirmation token: MD5(private_key + shop_process_id + "confirm" + amount + currency)
     */
    public function generateConfirmToken(string $shopProcessId, string $amount): string
    {
        return md5($this->privateKey . $shopProcessId . 'confirm' . $amount . $this->currency);
    }

    /**
     * Format amount as "165000.00" (string with 2 decimal places, no thousand separator)
     */
    public function formatAmount(float $amount): string
    {
        return number_format($amount, 2, '.', '');
    }

    // ─────────────────────────────────────────
    //  INITIATE PAYMENT  (POST /vpos/api/0.3/single_buy)
    // ─────────────────────────────────────────

    /**
     * Request a process_id from Bancard to load the iframe.
     *
     * @param string $shopProcessId    Generated by generateShopProcessId()
     * @param float  $amount           Amount in PYG (or configured currency)
     * @param string $description      Short description shown to buyer
     * @param string $returnUrl        URL Bancard redirects user after payment
     * @param string $cancelUrl        URL when user cancels
     * @return array  ['process_id' => '...', 'raw' => [...]]
     * @throws \Exception
     */
    public function singleBuy(
        string $shopProcessId,
        float $amount,
        string $description,
        string $returnUrl,
        string $cancelUrl
        ): array
    {
        $amountStr = $this->formatAmount($amount);
        $token = $this->generateOperationToken($shopProcessId, $amountStr);

        $payload = [
            'public_key' => $this->publicKey,
            'operation' => [
                'token' => $token,
                'shop_process_id' => $shopProcessId,
                'amount' => $amountStr,
                'currency' => $this->currency,
                'description' => $description,
                'return_url' => $returnUrl,
                'cancel_url' => $cancelUrl,
            ],
        ];

        $response = $this->post('vpos/api/0.3/single_buy', $payload);

        // Check for API-level errors
        if (($response['status'] ?? '') === 'error') {
            $msg = $this->extractErrorMessage($response);
            log_message('error', "Bancard singleBuy error: $msg | shop_process_id=$shopProcessId");
            throw new \Exception("Bancard: $msg");
        }

        // Extract the process_id returned in status=success response
        $processId = $response['process_id'] ?? null;

        // Some versions nest it differently
        if (!$processId && isset($response['messages'])) {
            foreach ($response['messages'] as $m) {
                if (isset($m['process_id'])) {
                    $processId = $m['process_id'];
                    break;
                }
            }
        }

        if (!$processId) {
            log_message('error', 'Bancard singleBuy: no process_id in response: ' . json_encode($response));
            throw new \Exception('Bancard returned no process_id. Check credentials and permissions.');
        }

        return [
            'process_id' => $processId,
            'shop_process_id' => $shopProcessId,
            'raw' => $response,
        ];
    }

    // ─────────────────────────────────────────
    //  IFRAME URL
    // ─────────────────────────────────────────

    /**
     * Build the checkout iframe URL using the process_id.
     * Embed this in an <iframe> on your payment page.
     */
    public function getIframeUrl(string $processId): string
    {
        $base = $this->testMode ?self::API_TEST : self::API_PRODUCTION;
        return "{$base}/checkout/new?process_id={$processId}&public_key={$this->publicKey}";
    }

    // ─────────────────────────────────────────
    //  VERIFY IPN CONFIRMATION
    // ─────────────────────────────────────────

    /**
     * Verify the IPN (confirmation) callback from Bancard.
     * Returns true if valid AND approved (response_code 0 / 00 / 000).
     *
     * @param array  $data             Decoded JSON body from Bancard IPN
     * @param string $shopProcessId    The shop_process_id we stored for this order
     * @param float  $expectedAmount   The amount we charged
     * @return bool
     */
    public function verifyConfirmation(array $data, string $shopProcessId, float $expectedAmount): bool
    {
        $confirmation = $data['confirmation'] ?? null;
        if (!$confirmation) {
            log_message('warning', 'Bancard IPN: no confirmation block in data');
            return false;
        }

        // Verify token
        $receivedToken = $data['confirmation']['token'] ?? null;
        $amountStr = $this->formatAmount($expectedAmount);
        $expectedToken = $this->generateConfirmToken($shopProcessId, $amountStr);

        if (!$receivedToken || !hash_equals($expectedToken, $receivedToken)) {
            log_message('error', "Bancard IPN: token mismatch. expected=$expectedToken received=$receivedToken");
            return false;
        }

        // Check response code (0 / 00 / 000 = APPROVED)
        $responseCode = (string)($confirmation['response_code'] ?? '');
        $approved = in_array($responseCode, ['0', '00', '000'], true);

        if (!$approved) {
            log_message('info', "Bancard IPN: payment NOT approved. response_code=$responseCode");
        }

        return $approved;
    }

    // ─────────────────────────────────────────
    //  HTTP (cURL, no Guzzle needed)
    // ─────────────────────────────────────────

    private function getBaseUrl(): string
    {
        return $this->testMode ?self::API_TEST : self::API_PRODUCTION;
    }

    private function post(string $endpoint, array $data): array
    {
        $url = rtrim($this->getBaseUrl(), '/') . '/' . ltrim($endpoint, '/');
        $json = json_encode($data);

        $ch = curl_init($url);
        curl_setopt_array($ch, [
            CURLOPT_POST => true,
            CURLOPT_POSTFIELDS => $json,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT => $this->timeout,
            CURLOPT_HTTPHEADER => [
                'Content-Type: application/json',
                'Accept: application/json',
                'Content-Length: ' . strlen($json),
            ],
            CURLOPT_SSL_VERIFYPEER => true,
        ]);

        $raw = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $curlErr = curl_error($ch);
        curl_close($ch);

        if ($curlErr) {
            log_message('error', "Bancard cURL error on $endpoint: $curlErr");
            throw new \Exception("Network error communicating with Bancard: $curlErr");
        }

        $decoded = json_decode($raw, true);
        if (json_last_error() !== JSON_ERROR_NONE) {
            log_message('error', "Bancard invalid JSON [$httpCode]: $raw");
            throw new \Exception("Invalid response from Bancard (HTTP $httpCode)");
        }

        return $decoded;
    }

    private function extractErrorMessage(array $response): string
    {
        $msgs = $response['messages'] ?? [];
        $parts = [];
        foreach ($msgs as $m) {
            if (!empty($m['dsc']))
                $parts[] = $m['dsc'];
            if (!empty($m['message']))
                $parts[] = $m['message'];
        }
        return $parts ? implode('. ', $parts) : 'Unknown Bancard API error';
    }
}
